on:
  push:
    tags:
      - 'v*' # push only tags starting with v

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['windows-latest', 'ubuntu-latest', 'macos-latest']
        include:
          - os: ubuntu-latest
            asset_name: markdownToQuiz_linux
          - os: windows-latest
            asset_name: markdownToQuiz_windows
          - os: macos-latest
            asset_name: markdownToQuiz_mac

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Set up Python environment
      run: python3 -m venv venv

    - name: Activate Python environment
      run: source venv/bin/activate

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Build with PyInstaller
      run: python3 -m PyInstaller --onefile --paths=src src/gui_quiz.py --name=${{ matrix.asset_name }}



    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false

    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: dist/${{ matrix.asset_name }}
        asset_name: ${{ matrix.asset_name }}
        tag: ${{ github.ref }}