name: Python CI

on:
  push:
    tags:
      - 'v*' # push only tags starting with v

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.11
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Build with PyInstaller
        run: pyinstaller --onefile --paths=src src/gui_quiz.py --name=markdownToQuiz_windows
      - name: Upload windows artifact
        uses: actions/upload-artifact@v2
        with:
          name: markdownToQuiz_windows
          path: dist/markdownToQuiz_windows.exe

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.11
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Build with PyInstaller
        run: pyinstaller --onefile --paths=src src/gui_quiz.py --name=markdownToQuiz_linux
      - name: Upload linux artifact
        uses: actions/upload-artifact@v2
        with:
          name: markdownToQuiz_linux
          path: dist/markdownToQuiz_linux

  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.11
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Build with PyInstaller
        run: pyinstaller --onefile --paths=src src/gui_quiz.py --name=markdownToQuiz_mac
      - name: Upload macos artifact
        uses: actions/upload-artifact@v2
        with:
          name: markdownToQuiz_mac
          path: dist/markdownToQuiz_mac

  upload-release:
    runs-on: ubuntu-latest
    needs: [build-windows, build-linux, build-macos]
    steps:
      - uses: actions/checkout@v2
      - name: Create release
        id: create_release
        uses: actions/create-release@master
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Download artifacts
        uses: actions/download-artifact@v1
        with:
          path: uploads

      - name: Upload windows binary
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./uploads/markdownToQuiz_windows.exe
          asset_name: markdownToQuiz_windows.exe
          asset_content_type: application/octet-stream
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload linux binary
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./uploads/markdownToQuiz_linux
          asset_name: markdownToQuiz_linux
          asset_content_type: application/octet-stream
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload macos binary
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./uploads/markdownToQuiz_mac
          asset_name: markdownToQuiz_mac
          asset_content_type: application/octet-stream
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
